/path_node:
  ros__parameters:
    coordenadas_x: [1.5,  1.5,  1.5,  3.0,  3.0, 3.0, 3.0, 4.0]
    coordenadas_y: [0.0, -0.8, -1.5, -1.5, -0.8, 0.8, 1.6, 1.6]
    lin_vel: [0.025, 0.0925]
    ang_vel: [0.290, 1.500]
    area: 10.0