/path_node:
  ros__parameters:
    coordenadas_x: [0.5, 0.5, 0.0, -0.5, -0.5, 0.0]
    coordenadas_y: [0.2, 0.6, 0.8, 0.6, 0.2, 0.0]
    lin_vel: [0.025, 0.370]
    ang_vel: [0.290, 3.000]
    area: 10.0