/path_node:
  ros__parameters:
    coordenadas_x: [0.75,  0.75,  .75,  1.5,  1.5, 1.5, 1.5, 2.0]
    coordenadas_y: [0.0, -0.4, -0.75, -0.75, -0.4, 0.4, 0.8, 0.8]
    lin_vel: [0.025, 0.0925]
    ang_vel: [0.290, 1.500]
    origen_robot: [-1.0,0.0]
    area_largo: 2.4
    area_ancho: 2.4