/path_node:
  ros__parameters:
    coordenadas_x: [2.0,  2.0,  2.0,  3.0, 4.0]
    coordenadas_y: [0.0, 1.0, 2.0, 2.0, 2.0]
    lin_vel: [0.025, 0.0925]
    ang_vel: [0.290, 1.500]
    origen_robot: [-2.41, -2.0]
    area_largo: 4.81
    area_ancho: 4.81